src/Entity/Motifs.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\MotifsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MotifsRepository::class)
 * @ApiResource
 */
class Motifs
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mot_libelle;

    /**
     * @ORM\OneToMany(targetEntity=Visites::class, mappedBy="vst_motif")
     */
    private $mot_visites;

    public function __construct()
    {
        $this->mot_visites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMotLibelle(): ?string
    {
        return $this->mot_libelle;
    }

    public function setMotLibelle(string $mot_libelle): self
    {
        $this->mot_libelle = $mot_libelle;

        return $this;
    }

    /**
     * @return Collection|Visites[]
     */
    public function getMotVisites(): Collection
    {
        return $this->mot_visites;
    }

    public function addMotVisite(Visites $motVisite): self
    {
        if (!$this->mot_visites->contains($motVisite)) {
            $this->mot_visites[] = $motVisite;
            $motVisite->setVstMotif($this);
        }

        return $this;
    }

    public function removeMotVisite(Visites $motVisite): self
    {
        if ($this->mot_visites->removeElement($motVisite)) {
            // set the owning side to null (unless already changed)
            if ($motVisite->getVstMotif() === $this) {
                $motVisite->setVstMotif(null);
            }
        }

        return $this;
    }
}

src/Form/MotifsType.php
<?php

namespace App\Form;

use App\Entity\Motifs;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MotifsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('mot_libelle')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Motifs::class,
        ]);
    }
}

src/Controller/MotifsController.php
<?php

namespace App\Controller;

use App\Entity\Motifs;
use App\Form\MotifsType;
use App\Repository\MotifsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/motifs")
 */
class MotifsController extends AbstractController
{
    /**
     * @Route("/", name="motifs_index", methods={"GET"})
     */
    public function index(MotifsRepository $motifsRepository): Response
    {
        return $this->render('motifs/index.html.twig', [
            'motifs' => $motifsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="motifs_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $motif = new Motifs();
        $form = $this->createForm(MotifsType::class, $motif);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($motif);
            $entityManager->flush();

            return $this->redirectToRoute('motifs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('motifs/new.html.twig', [
            'motif' => $motif,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="motifs_show", methods={"GET"})
     */
    public function show(Motifs $motif): Response
    {
        return $this->render('motifs/show.html.twig', [
            'motif' => $motif,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="motifs_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Motifs $motif, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(MotifsType::class, $motif);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('motifs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('motifs/edit.html.twig', [
            'motif' => $motif,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="motifs_delete", methods={"POST"})
     */
    public function delete(Request $request, Motifs $motif, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$motif->getId(), $request->request->get('_token'))) {
            $entityManager->remove($motif);
            $entityManager->flush();
        }

        return $this->redirectToRoute('motifs_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/motifs/_delete_form.html.twig
<form method="post" action="{{ path('motifs_delete', {'id': motif.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ motif.id) }}">
    <button class="btn">Delete</button>
</form>

templates/motifs/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/motifs/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Motifs{% endblock %}

{% block body %}
    <h1>Edit Motifs</h1>

    {{ include('motifs/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('motifs_index') }}">back to list</a>

    {{ include('motifs/_delete_form.html.twig') }}
{% endblock %}

templates/motifs/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Motifs index{% endblock %}

{% block body %}
    <h1>Motifs index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Mot_libelle</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for motif in motifs %}
            <tr>
                <td>{{ motif.id }}</td>
                <td>{{ motif.motLibelle }}</td>
                <td>
                    <a href="{{ path('motifs_show', {'id': motif.id}) }}">show</a>
                    <a href="{{ path('motifs_edit', {'id': motif.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="3">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('motifs_new') }}">Create new</a>
{% endblock %}

templates/motifs/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Motifs{% endblock %}

{% block body %}
    <h1>Create new Motifs</h1>

    {{ include('motifs/_form.html.twig') }}

    <a href="{{ path('motifs_index') }}">back to list</a>
{% endblock %}

templates/motifs/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Motifs{% endblock %}

{% block body %}
    <h1>Motifs</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ motif.id }}</td>
            </tr>
            <tr>
                <th>Mot_libelle</th>
                <td>{{ motif.motLibelle }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('motifs_index') }}">back to list</a>

    <a href="{{ path('motifs_edit', {'id': motif.id}) }}">edit</a>

    {{ include('motifs/_delete_form.html.twig') }}
{% endblock %}