src/Entity/Praticiens.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\PraticiensRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PraticiensRepository::class)
 * @ApiResource
 */
class Praticiens
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pra_nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pra_prenom;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $pra_tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pra_mail;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pra_rue;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pra_codePostal;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pra_ville;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $pra_coefNotoriete;

    /**
     * @ORM\OneToMany(targetEntity=Visites::class, mappedBy="vst_praticien")
     */
    private $pra_visites;

    public function __construct()
    {
        $this->pra_visites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPraNom(): ?string
    {
        return $this->pra_nom;
    }

    public function setPraNom(string $pra_nom): self
    {
        $this->pra_nom = $pra_nom;

        return $this;
    }

    public function getPraPrenom(): ?string
    {
        return $this->pra_prenom;
    }

    public function setPraPrenom(string $pra_prenom): self
    {
        $this->pra_prenom = $pra_prenom;

        return $this;
    }

    public function getPraTel(): ?string
    {
        return $this->pra_tel;
    }

    public function setPraTel(?string $pra_tel): self
    {
        $this->pra_tel = $pra_tel;

        return $this;
    }

    public function getPraMail(): ?string
    {
        return $this->pra_mail;
    }

    public function setPraMail(?string $pra_mail): self
    {
        $this->pra_mail = $pra_mail;

        return $this;
    }

    public function getPraRue(): ?string
    {
        return $this->pra_rue;
    }

    public function setPraRue(?string $pra_rue): self
    {
        $this->pra_rue = $pra_rue;

        return $this;
    }

    public function getPraCodePostal(): ?string
    {
        return $this->pra_codePostal;
    }

    public function setPraCodePostal(?string $pra_codePostal): self
    {
        $this->pra_codePostal = $pra_codePostal;

        return $this;
    }

    public function getPraVille(): ?string
    {
        return $this->pra_ville;
    }

    public function setPraVille(?string $pra_ville): self
    {
        $this->pra_ville = $pra_ville;

        return $this;
    }

    public function getPraCoefNotoriete(): ?int
    {
        return $this->pra_coefNotoriete;
    }

    public function setPraCoefNotoriete(?int $pra_coefNotoriete): self
    {
        $this->pra_coefNotoriete = $pra_coefNotoriete;

        return $this;
    }

    /**
     * @return Collection|Visites[]
     */
    public function getPraVisites(): Collection
    {
        return $this->pra_visites;
    }

    public function addPraVisite(Visites $praVisite): self
    {
        if (!$this->pra_visites->contains($praVisite)) {
            $this->pra_visites[] = $praVisite;
            $praVisite->setVstPraticien($this);
        }

        return $this;
    }

    public function removePraVisite(Visites $praVisite): self
    {
        if ($this->pra_visites->removeElement($praVisite)) {
            // set the owning side to null (unless already changed)
            if ($praVisite->getVstPraticien() === $this) {
                $praVisite->setVstPraticien(null);
            }
        }

        return $this;
    }
}

src/Form/PraticiensType.php
<?php

namespace App\Form;

use App\Entity\Praticiens;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PraticiensType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('pra_nom')
            ->add('pra_prenom')
            ->add('pra_tel')
            ->add('pra_mail')
            ->add('pra_rue')
            ->add('pra_codePostal')
            ->add('pra_ville')
            ->add('pra_coefNotoriete')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Praticiens::class,
        ]);
    }
}

src/Controller/PraticiensController.php
<?php

namespace App\Controller;

use App\Entity\Praticiens;
use App\Form\PraticiensType;
use App\Repository\PraticiensRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/praticiens")
 */
class PraticiensController extends AbstractController
{
    /**
     * @Route("/", name="praticiens_index", methods={"GET"})
     */
    public function index(PraticiensRepository $praticiensRepository): Response
    {
        return $this->render('praticiens/index.html.twig', [
            'praticiens' => $praticiensRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="praticiens_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $praticien = new Praticiens();
        $form = $this->createForm(PraticiensType::class, $praticien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($praticien);
            $entityManager->flush();

            return $this->redirectToRoute('praticiens_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('praticiens/new.html.twig', [
            'praticien' => $praticien,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="praticiens_show", methods={"GET"})
     */
    public function show(Praticiens $praticien): Response
    {
        return $this->render('praticiens/show.html.twig', [
            'praticien' => $praticien,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="praticiens_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Praticiens $praticien, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PraticiensType::class, $praticien);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('praticiens_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('praticiens/edit.html.twig', [
            'praticien' => $praticien,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="praticiens_delete", methods={"POST"})
     */
    public function delete(Request $request, Praticiens $praticien, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$praticien->getId(), $request->request->get('_token'))) {
            $entityManager->remove($praticien);
            $entityManager->flush();
        }

        return $this->redirectToRoute('praticiens_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/praticiens/_delete_form.html.twig
<form method="post" action="{{ path('praticiens_delete', {'id': praticien.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ praticien.id) }}">
    <button class="btn">Delete</button>
</form>

templates/praticiens/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/praticiens/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Praticiens{% endblock %}

{% block body %}
    <h1>Edit Praticiens</h1>

    {{ include('praticiens/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('praticiens_index') }}">back to list</a>

    {{ include('praticiens/_delete_form.html.twig') }}
{% endblock %}

templates/praticiens/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Praticiens index{% endblock %}

{% block body %}
    <h1>Praticiens index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Pra_nom</th>
                <th>Pra_prenom</th>
                <th>Pra_tel</th>
                <th>Pra_mail</th>
                <th>Pra_rue</th>
                <th>Pra_codePostal</th>
                <th>Pra_ville</th>
                <th>Pra_coefNotoriete</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for praticien in praticiens %}
            <tr>
                <td>{{ praticien.id }}</td>
                <td>{{ praticien.praNom }}</td>
                <td>{{ praticien.praPrenom }}</td>
                <td>{{ praticien.praTel }}</td>
                <td>{{ praticien.praMail }}</td>
                <td>{{ praticien.praRue }}</td>
                <td>{{ praticien.praCodePostal }}</td>
                <td>{{ praticien.praVille }}</td>
                <td>{{ praticien.praCoefNotoriete }}</td>
                <td>
                    <a href="{{ path('praticiens_show', {'id': praticien.id}) }}">show</a>
                    <a href="{{ path('praticiens_edit', {'id': praticien.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('praticiens_new') }}">Create new</a>
{% endblock %}

templates/praticiens/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Praticiens{% endblock %}

{% block body %}
    <h1>Create new Praticiens</h1>

    {{ include('praticiens/_form.html.twig') }}

    <a href="{{ path('praticiens_index') }}">back to list</a>
{% endblock %}

templates/praticiens/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Praticiens{% endblock %}

{% block body %}
    <h1>Praticiens</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ praticien.id }}</td>
            </tr>
            <tr>
                <th>Pra_nom</th>
                <td>{{ praticien.praNom }}</td>
            </tr>
            <tr>
                <th>Pra_prenom</th>
                <td>{{ praticien.praPrenom }}</td>
            </tr>
            <tr>
                <th>Pra_tel</th>
                <td>{{ praticien.praTel }}</td>
            </tr>
            <tr>
                <th>Pra_mail</th>
                <td>{{ praticien.praMail }}</td>
            </tr>
            <tr>
                <th>Pra_rue</th>
                <td>{{ praticien.praRue }}</td>
            </tr>
            <tr>
                <th>Pra_codePostal</th>
                <td>{{ praticien.praCodePostal }}</td>
            </tr>
            <tr>
                <th>Pra_ville</th>
                <td>{{ praticien.praVille }}</td>
            </tr>
            <tr>
                <th>Pra_coefNotoriete</th>
                <td>{{ praticien.praCoefNotoriete }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('praticiens_index') }}">back to list</a>

    <a href="{{ path('praticiens_edit', {'id': praticien.id}) }}">edit</a>

    {{ include('praticiens/_delete_form.html.twig') }}
{% endblock %}