src/Entity/Visites.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\VisitesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=VisitesRepository::class)
 * @ApiResource
 */
class Visites
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="date")
     */
    private $vst_dateVisite;

    /**
     * @ORM\Column(type="text")
     */
    private $vst_commentaire;

    /**
     * @ORM\ManyToOne(targetEntity=Praticiens::class, inversedBy="pra_visites")
     */
    private $vst_praticien;

    /**
     * @ORM\ManyToOne(targetEntity=Motifs::class, inversedBy="mot_visites")
     */
    private $vst_motif;

    /**
     * @ORM\ManyToOne(targetEntity=Visiteurs::class, inversedBy="vis_visites")
     */
    private $vst_visiteur;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getVstDateVisite(): ?\DateTimeInterface
    {
        return $this->vst_dateVisite;
    }

    public function setVstDateVisite(\DateTimeInterface $vst_dateVisite): self
    {
        $this->vst_dateVisite = $vst_dateVisite;

        return $this;
    }

    public function getVstCommentaire(): ?string
    {
        return $this->vst_commentaire;
    }

    public function setVstCommentaire(string $vst_commentaire): self
    {
        $this->vst_commentaire = $vst_commentaire;

        return $this;
    }

    public function getVstPraticien(): ?Praticiens
    {
        return $this->vst_praticien;
    }

    public function setVstPraticien(?Praticiens $vst_praticien): self
    {
        $this->vst_praticien = $vst_praticien;

        return $this;
    }

    public function getVstMotif(): ?Motifs
    {
        return $this->vst_motif;
    }

    public function setVstMotif(?Motifs $vst_motif): self
    {
        $this->vst_motif = $vst_motif;

        return $this;
    }

    public function getVstVisiteur(): ?Visiteurs
    {
        return $this->vst_visiteur;
    }

    public function setVstVisiteur(?Visiteurs $vst_visiteur): self
    {
        $this->vst_visiteur = $vst_visiteur;

        return $this;
    }
}

src/Form/VisitesType.php
<?php

namespace App\Form;

use App\Entity\Visites;
use App\Entity\Praticiens;
use App\Entity\Motifs;
use App\Entity\Visiteurs;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VisitesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('vst_dateVisite')
            ->add('vst_commentaire')
            ->add('vst_praticien', EntityType::class, ['class' => Praticiens::class, 'choice_label' => 'pra_nom'])
            ->add('vst_motif', EntityType::class, ['class' => Motifs::class, 'choice_label' => 'mot_libelle'])
            ->add('vst_visiteur' , EntityType::class, ['class' => Visiteurs::class, 'choice_label' => 'vis_nom'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Visites::class,
        ]);
    }
}

src/Controller/VisitesController.php
<?php

namespace App\Controller;

use App\Entity\Visites;
use App\Form\VisitesType;
use App\Repository\VisitesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/visites")
 */
class VisitesController extends AbstractController
{
    /**
     * @Route("/", name="visites_index", methods={"GET"})
     */
    public function index(VisitesRepository $visitesRepository): Response
    {
        return $this->render('visites/index.html.twig', [
            'visites' => $visitesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="visites_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $visite = new Visites();
        $form = $this->createForm(VisitesType::class, $visite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($visite);
            $entityManager->flush();

            return $this->redirectToRoute('visites_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('visites/new.html.twig', [
            'visite' => $visite,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="visites_show", methods={"GET"})
     */
    public function show(Visites $visite): Response
    {
        return $this->render('visites/show.html.twig', [
            'visite' => $visite,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="visites_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Visites $visite, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VisitesType::class, $visite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('visites_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('visites/edit.html.twig', [
            'visite' => $visite,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="visites_delete", methods={"POST"})
     */
    public function delete(Request $request, Visites $visite, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$visite->getId(), $request->request->get('_token'))) {
            $entityManager->remove($visite);
            $entityManager->flush();
        }

        return $this->redirectToRoute('visites_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/visites/_delete_form.html.twig
<form method="post" action="{{ path('visites_delete', {'id': visite.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ visite.id) }}">
    <button class="btn">Delete</button>
</form>

templates/visites/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/visites/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Visites{% endblock %}

{% block body %}
    <h1>Edit Visites</h1>

    {{ include('visites/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('visites_index') }}">back to list</a>

    {{ include('visites/_delete_form.html.twig') }}
{% endblock %}

templates/visites/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Visites index{% endblock %}

{% block body %}
    <h1>Visites index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Vst_dateVisite</th>
                <th>Vst_commentaire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for visite in visites %}
            <tr>
                <td>{{ visite.id }}</td>
                <td>{{ visite.vstDateVisite ? visite.vstDateVisite|date('Y-m-d') : '' }}</td>
                <td>{{ visite.vstCommentaire }}</td>
                <td>
                    <a href="{{ path('visites_show', {'id': visite.id}) }}">show</a>
                    <a href="{{ path('visites_edit', {'id': visite.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('visites_new') }}">Create new</a>
{% endblock %}

templates/visites/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Visites{% endblock %}

{% block body %}
    <h1>Create new Visites</h1>

    {{ include('visites/_form.html.twig') }}

    <a href="{{ path('visites_index') }}">back to list</a>
{% endblock %}

templates/visites/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Visites{% endblock %}

{% block body %}
    <h1>Visites</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ visite.id }}</td>
            </tr>
            <tr>
                <th>Vst_dateVisite</th>
                <td>{{ visite.vstDateVisite ? visite.vstDateVisite|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Vst_commentaire</th>
                <td>{{ visite.vstCommentaire }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('visites_index') }}">back to list</a>

    <a href="{{ path('visites_edit', {'id': visite.id}) }}">edit</a>

    {{ include('visites/_delete_form.html.twig') }}
{% endblock %}