src/Entity/Visiteurs.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\VisiteursRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=VisiteursRepository::class)
 * @ApiResource
 */
class Visiteurs implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vis_nom;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vis_prenom;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $vis_tel;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $vis_dateEmbauche;

    /**
     * @ORM\OneToMany(targetEntity=Visites::class, mappedBy="vst_visiteur")
     */
    private $vis_visites;

    /**
     * @ORM\ManyToMany(targetEntity=Praticiens::class)
     */
    private $vis_praticiens;

    public function __construct()
    {
        $this->vis_visites = new ArrayCollection();
        $this->vis_praticiens = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getVisNom(): ?string
    {
        return $this->vis_nom;
    }

    public function setVisNom(?string $vis_nom): self
    {
        $this->vis_nom = $vis_nom;

        return $this;
    }

    public function getVisPrenom(): ?string
    {
        return $this->vis_prenom;
    }

    public function setVisPrenom(?string $vis_prenom): self
    {
        $this->vis_prenom = $vis_prenom;

        return $this;
    }

    public function getVisTel(): ?string
    {
        return $this->vis_tel;
    }

    public function setVisTel(?string $vis_tel): self
    {
        $this->vis_tel = $vis_tel;

        return $this;
    }

    public function getVisDateEmbauche(): ?string
    {
        return $this->vis_dateEmbauche;
    }

    public function setVisDateEmbauche(?string $vis_dateEmbauche): self
    {
        $this->vis_dateEmbauche = $vis_dateEmbauche;

        return $this;
    }

    /**
     * @return Collection|Visites[]
     */
    public function getVisVisites(): Collection
    {
        return $this->vis_visites;
    }

    public function addVisVisite(Visites $visVisite): self
    {
        if (!$this->vis_visites->contains($visVisite)) {
            $this->vis_visites[] = $visVisite;
            $visVisite->setVstVisiteur($this);
        }

        return $this;
    }

    public function removeVisVisite(Visites $visVisite): self
    {
        if ($this->vis_visites->removeElement($visVisite)) {
            // set the owning side to null (unless already changed)
            if ($visVisite->getVstVisiteur() === $this) {
                $visVisite->setVstVisiteur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Praticiens[]
     */
    public function getVisPraticiens(): Collection
    {
        return $this->vis_praticiens;
    }

    public function addVisPraticien(Praticiens $visPraticien): self
    {
        if (!$this->vis_praticiens->contains($visPraticien)) {
            $this->vis_praticiens[] = $visPraticien;
        }

        return $this;
    }

    public function removeVisPraticien(Praticiens $visPraticien): self
    {
        $this->vis_praticiens->removeElement($visPraticien);

        return $this;
    }
}

src/Form/VisiteursType.php
<?php

namespace App\Form;

use App\Entity\Visiteurs;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VisiteursType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email')
            ->add('password')
            ->add('vis_nom')
            ->add('vis_prenom')
            ->add('vis_tel')
            ->add('vis_dateEmbauche')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Visiteurs::class,
        ]);
    }
}

src/Controller/VisiteursController.php
<?php

namespace App\Controller;

use App\Entity\Visiteurs;
use App\Form\VisiteursType;
use App\Repository\VisiteursRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/visiteurs")
 */
class VisiteursController extends AbstractController
{
    /**
     * @Route("/", name="visiteurs_index", methods={"GET"})
     */
    public function index(VisiteursRepository $visiteursRepository): Response
    {
        return $this->render('visiteurs/index.html.twig', [
            'visiteurs' => $visiteursRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="visiteurs_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $visiteur = new Visiteurs();
        $form = $this->createForm(VisiteursType::class, $visiteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($visiteur);
            $entityManager->flush();

            return $this->redirectToRoute('visiteurs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('visiteurs/new.html.twig', [
            'visiteur' => $visiteur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="visiteurs_show", methods={"GET"})
     */
    public function show(Visiteurs $visiteur): Response
    {
        return $this->render('visiteurs/show.html.twig', [
            'visiteur' => $visiteur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="visiteurs_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Visiteurs $visiteur, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VisiteursType::class, $visiteur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('visiteurs_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('visiteurs/edit.html.twig', [
            'visiteur' => $visiteur,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="visiteurs_delete", methods={"POST"})
     */
    public function delete(Request $request, Visiteurs $visiteur, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$visiteur->getId(), $request->request->get('_token'))) {
            $entityManager->remove($visiteur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('visiteurs_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/visiteurs/_delete_form.html.twig
<form method="post" action="{{ path('visiteurs_delete', {'id': visiteur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ visiteur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/visiteurs/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/visiteurs/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Visiteurs{% endblock %}

{% block body %}
    <h1>Edit Visiteurs</h1>

    {{ include('visiteurs/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('visiteurs_index') }}">back to list</a>

    {{ include('visiteurs/_delete_form.html.twig') }}
{% endblock %}

templates/visiteurs/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Visiteurs index{% endblock %}

{% block body %}
    <h1>Visiteurs index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Password</th>
                <th>Vis_nom</th>
                <th>Vis_prenom</th>
                <th>Vis_tel</th>
                <th>Vis_dateEmbauche</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for visiteur in visiteurs %}
            <tr>
                <td>{{ visiteur.id }}</td>
                <td>{{ visiteur.email }}</td>
                <td>{{ visiteur.roles ? visiteur.roles|json_encode : '' }}</td>
                <td>{{ visiteur.password }}</td>
                <td>{{ visiteur.visNom }}</td>
                <td>{{ visiteur.visPrenom }}</td>
                <td>{{ visiteur.visTel }}</td>
                <td>{{ visiteur.visDateEmbauche }}</td>
                <td>
                    <a href="{{ path('visiteurs_show', {'id': visiteur.id}) }}">show</a>
                    <a href="{{ path('visiteurs_edit', {'id': visiteur.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('visiteurs_new') }}">Create new</a>
{% endblock %}

templates/visiteurs/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Visiteurs{% endblock %}

{% block body %}
    <h1>Create new Visiteurs</h1>

    {{ include('visiteurs/_form.html.twig') }}

    <a href="{{ path('visiteurs_index') }}">back to list</a>
{% endblock %}

templates/visiteurs/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Visiteurs{% endblock %}

{% block body %}
    <h1>Visiteurs</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ visiteur.id }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ visiteur.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ visiteur.roles ? visiteur.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Password</th>
                <td>{{ visiteur.password }}</td>
            </tr>
            <tr>
                <th>Vis_nom</th>
                <td>{{ visiteur.visNom }}</td>
            </tr>
            <tr>
                <th>Vis_prenom</th>
                <td>{{ visiteur.visPrenom }}</td>
            </tr>
            <tr>
                <th>Vis_tel</th>
                <td>{{ visiteur.visTel }}</td>
            </tr>
            <tr>
                <th>Vis_dateEmbauche</th>
                <td>{{ visiteur.visDateEmbauche }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('visiteurs_index') }}">back to list</a>

    <a href="{{ path('visiteurs_edit', {'id': visiteur.id}) }}">edit</a>

    {{ include('visiteurs/_delete_form.html.twig') }}
{% endblock %}